apiVersion: database.platform.ohanyere.io/v1alpha1
kind: PostgreSQLClaim
metadata:
  name: system-api-postgres
  labels:
    app.kubernetes.io/name: system-api
    finops.ohanyere.io/cost-center: developer-experience
spec:
  environment: dev
  databaseName: system-api
  size: small
  version: "16"
  backup:
    enabled: true
    retentionDays: 14
