apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: system-api
  labels:
    app.kubernetes.io/name: system-api
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: system-api
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
