apiVersion: v1
kind: ServiceAccount
metadata:
  name: system-api
  labels:
    app.kubernetes.io/name: system-api
    finops.ohanyere.io/cost-center: developer-experience
automountServiceAccountToken: false
