apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: system-api
spec:
  replicas: 1
  strategy:
    canary:
      steps:
        - setWeight: 100
  template:
    spec:
      serviceAccountName: system-api-dev
      containers:
        - name: api
          image: kuberpull/system-api:dev
          env:
            - name: LOG_LEVEL
              value: debug
          resources:
            requests:
              cpu: 50m
              memory: 96Mi
            limits:
              cpu: 250m
              memory: 256Mi
